import {describe,it,expect,vi} from 'vitest';
import {mkdtemp,writeFile,readFile,symlink,chmod} from 'node:fs/promises';
import {join} from 'node:path';import {tmpdir} from 'node:os';
import {loadConfig} from '../src/config.js';import {WistiaClient} from '../src/api/client.js';
import {ALL_TOOLS,validateArguments} from '../src/tools/index.js';import {buildServer} from '../src/server.js';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';
const config=()=>loadConfig({WISTIA_API_TOKEN:'fixture-private-value',WISTIA_MIN_REQUEST_INTERVAL_MS:'0'});
const response=(v:unknown,status=200,headers:Record<string,string>={})=>new Response(JSON.stringify(v),{status,headers});
const invoke=async(n:string,a:Record<string,unknown>,f:any)=>{const t=ALL_TOOLS.find(t=>t.name===n)!;validateArguments(t,a);return t.handler(a,new WistiaClient(config(),f));};
async function connect(c=config(),f:any=vi.fn()){const s=buildServer(c,new WistiaClient(c,f));const[a,b]=InMemoryTransport.createLinkedPair();await s.connect(b);const client=new Client({name:'fixture',version:'1'});await client.connect(a);return{client,close:async()=>{await client.close();await s.close();}};}
describe('Wistia provider routing and shared safeguards',()=>{
 it('allows nonmutating caption searches in read-only mode',async()=>{const c=config();c.readOnly=true;const f=vi.fn(async()=>response({results:[]}));const{client,close}=await connect(c,f);try{const r=await client.callTool({name:'find_caption_matches',arguments:{media_ids:['a'],target_text:'Approved wording'}});expect(r.isError).not.toBe(true);expect(f).toHaveBeenCalledTimes(1);}finally{await close();}});
 it('refuses stale-version placeholders and incomplete caption windows before editing',async()=>{const f=vi.fn();for(const a of [{expected_version:0,edits:[{target_text:'a',replacement_text:'b'}]},{expected_version:1,edits:[{target_text:'a',replacement_text:'b',start_ms:5}]},{expected_version:1,edits:[{target_text:'a',replacement_text:'b',start_ms:5,end_ms:4}]}])await expect(invoke('edit_captions_text',{media_hashed_id:'a',language_code:'en',...a},f)).rejects.toThrow();expect(f).not.toHaveBeenCalled();});

 it('retains modern path, private Bearer auth and dated version',async()=>{const f=vi.fn(async(u:any,i:any)=>{expect(String(u)).toBe('https://api.wistia.com/modern/medias/abc');expect(i.headers.Authorization).toBe('Bearer fixture-private-value');expect(i.headers['X-Wistia-Api-Version']).toBe('2026-09');expect(i.redirect).toBe('error');return response({hashed_id:'abc'});});expect(await invoke('get_media',{media_hashed_id:'abc'},f)).toEqual({hashed_id:'abc'});});
 it('refuses arbitrary routes before sending credentials',async()=>{const f=vi.fn();for(const p of ['https://evil.example/medias','/../medias','/medias/a%2Fb','/medias/a%5Cb'])await expect(new WistiaClient(config(),f).request('GET',p)).rejects.toThrow('Unsupported');expect(f).not.toHaveBeenCalled();});
 it('serializes repeated arrays and cursor fields',async()=>{await invoke('list_media',{hashed_ids:['a','b'],cursor:{after:'opaque'}},async(u:any)=>{const x=new URL(u);expect(x.searchParams.getAll('hashed_ids[]')).toEqual(['a','b']);expect(x.searchParams.get('cursor[after]')).toBe('opaque');return response([]);});});
 it('refuses mixed cursor/page and cursor/all_pages',async()=>{const f=vi.fn();for(const a of [{page:1},{all_pages:true}])await expect(invoke('list_media',{...a,cursor:{enabled:1}},f)).rejects.toThrow('cannot be combined');expect(f).not.toHaveBeenCalled();});
 it('uses current caption_file/language fields',async()=>{const f=vi.fn(async(_u:any,i:any)=>{expect(JSON.parse(i.body)).toEqual({caption_file:'Fixture SRT',language:'eng'});return response({});});await invoke('create_captions',{media_hashed_id:'a',caption_file:'Fixture SRT',language:'eng'},f);await expect(invoke('create_captions',{media_hashed_id:'a',language:'eng'},f)).rejects.toThrow('caption_file');expect(f).toHaveBeenCalledTimes(1);});
 it('rejects obsolete bulk-tag fields',async()=>{const f=vi.fn(async(_u:any,i:any)=>{expect(JSON.parse(i.body)).toEqual({hashed_ids:['a'],tag_names:['approved']});return response({});});await invoke('bulk_tag',{hashed_ids:['a'],tag_names:['approved']},f);await expect(invoke('bulk_tag',{media_hashed_ids:['a'],tags:['old']},f)).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1);});
 it('uses form upload without an access_token argument',async()=>{const f=vi.fn(async(u:any,i:any)=>{expect(String(u)).toBe('https://upload.wistia.com/');expect(i.headers['Content-Type']).toBe('application/x-www-form-urlencoded');expect(new URLSearchParams(i.body).get('url')).toBe('https://example.com/video.mp4');expect(new URLSearchParams(i.body).has('access_token')).toBe(false);return response({});});await invoke('upload_media',{url:'https://example.com/video.mp4'},f);await expect(invoke('upload_media',{url:'https://example.com/video.mp4',access_token:'not-allowed'},f)).rejects.toThrow();});
 it('uploads regular local bytes using multipart',async()=>{const p=await mkdtemp(join(tmpdir(),'wistia-upload-'));await writeFile(join(p,'fixture.txt'),'actual-bytes');await invoke('upload_media_file',{file:join(p,'fixture.txt'),name:'Fixture'},async(u:any,i:any)=>{expect(String(u)).toBe('https://upload.wistia.com/');expect(i.headers['Content-Type']).toBeUndefined();expect(await i.body.get('file').text()).toBe('actual-bytes');expect(i.body.get('name')).toBe('Fixture');return response({});});});
 it('refuses symlink uploads before a mutation',async()=>{const p=await mkdtemp(join(tmpdir(),'wistia-link-'));await writeFile(join(p,'target'),'x');await symlink(join(p,'target'),join(p,'link'));const f=vi.fn();await expect(invoke('upload_media_file',{file:join(p,'link')},f)).rejects.toThrow('regular');expect(f).not.toHaveBeenCalled();});
 it('collects bounded native pages with accurate partial continuation',async()=>{const f=vi.fn(async(u:any)=>response(Number(new URL(u).searchParams.get('page'))===1?[{id:1},{id:2}]:[{id:3},{id:4}]));const x:any=await invoke('list_media',{per_page:2,all_pages:true,max_items:3},f);expect(x.records).toEqual([{id:1},{id:2},{id:3}]);expect(x.resume).toEqual({page:2,per_page:2,skip:1});expect(x.truncated).toBe(true);expect(f).toHaveBeenCalledTimes(2);});
 it('stops repeated full pages',async()=>{const f=vi.fn(async()=>response([{id:1}]));await expect(invoke('list_media',{per_page:1,all_pages:true,max_items:5},f)).rejects.toThrow('repeated');expect(f).toHaveBeenCalledTimes(2);});
 it('rejects unknown filters and invalid local paging bounds',()=>{const t=ALL_TOOLS.find(t=>t.name==='list_media')!;for(const a of [{per_page:101},{page:0},{unknown:'x'}])expect(()=>validateArguments(t,a)).toThrow();});
 it('honors bounded Retry-After on reads',async()=>{let n=0;const f=vi.fn(async()=>++n===1?response({},429,{'retry-after':'0'}):response({id:1}));expect(await new WistiaClient(config(),f,async()=>{}).request('GET','/account')).toEqual({id:1});expect(f).toHaveBeenCalledTimes(2);});
 it('never automatically repeats writes',async()=>{for(const fail of [()=>Promise.resolve(response({},429,{'retry-after':'0'})),()=>Promise.reject(new Error('lost response'))]){const f=vi.fn(fail)as any;await expect(new WistiaClient(config(),f).request('DELETE','/medias/a')).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1);}});
 it('redacts configured and returned credentials',()=>{expect(new WistiaClient(config()).sanitize({token:'new-private',nested:{message:'fixture-private-value'}})).toEqual({token:'[redacted]',nested:{message:'[redacted]'}});});
 it('isolates private named accounts',async()=>{const c=loadConfig({WISTIA_ACCOUNTS:JSON.stringify([{name:'a',api_token:'fixture-a'},{name:'b',api_token:'fixture-b'}]),WISTIA_MIN_REQUEST_INTERVAL_MS:'0'});const f=vi.fn(async(_u:any,i:any)=>{expect(i.headers.Authorization).toBe('Bearer fixture-b');return response({});});await new WistiaClient(c,f).request('GET','/account',[],undefined,'b');await expect(new WistiaClient(c,f).request('GET','/account',[],undefined,'missing')).rejects.toThrow('Unknown account');expect(f).toHaveBeenCalledTimes(1);});
 it('saves newly generated credentials only in an exclusive private file',async()=>{const p=await mkdtemp(join(tmpdir(),'wistia-grant-'));await chmod(p,0o700);const file=join(p,'grant.json');const f=vi.fn(async()=>response({token:'fixture-created-private-token'}));expect(await invoke('create_expiring_access_token',{secret_result_file:file},f)).toEqual({private_result_saved:true,credentials_returned_to_client:false});expect(JSON.parse(await readFile(file,'utf8')).token).toBe('fixture-created-private-token');await expect(invoke('create_expiring_access_token',{secret_result_file:file},f)).rejects.toThrow('new private file');expect(f).toHaveBeenCalledTimes(1);});
 it('discovers the actual tools and rejects unconfirmed mutations',async()=>{const f=vi.fn();const{client,close}=await connect(config(),f);try{const x=await client.listTools();expect(x.tools).toHaveLength(169);expect(x.tools.filter(t=>t.annotations?.readOnlyHint)).toHaveLength(86);const r=await client.callTool({name:'delete_media',arguments:{media_hashed_id:'a'}});expect(r.isError).toBe(true);expect(JSON.stringify(r)).toContain('confirm: true');expect(f).not.toHaveBeenCalled();}finally{await close();}});
 it('hides writes in read-only mode and refuses direct bypass calls',async()=>{const c=config();c.readOnly=true;const f=vi.fn();const{client,close}=await connect(c,f);try{expect((await client.listTools()).tools).toHaveLength(86);const r=await client.callTool({name:'delete_media',arguments:{media_hashed_id:'a',confirm:true}});expect(r.isError).toBe(true);expect(JSON.stringify(r)).toContain('READ_ONLY');expect(f).not.toHaveBeenCalled();}finally{await close();}});
});
